################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_ISO7816_Password.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_AAR.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Email.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Geo.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_MyApp.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_SMS.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Text.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_URI.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Vcard.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_STProprietary_feature.c \
C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_TagType4.c 

OBJS += \
./Middlewares/lib_NDEF/lib_ISO7816_Password.o \
./Middlewares/lib_NDEF/lib_NDEF.o \
./Middlewares/lib_NDEF/lib_NDEF_AAR.o \
./Middlewares/lib_NDEF/lib_NDEF_Email.o \
./Middlewares/lib_NDEF/lib_NDEF_Geo.o \
./Middlewares/lib_NDEF/lib_NDEF_MyApp.o \
./Middlewares/lib_NDEF/lib_NDEF_SMS.o \
./Middlewares/lib_NDEF/lib_NDEF_Text.o \
./Middlewares/lib_NDEF/lib_NDEF_URI.o \
./Middlewares/lib_NDEF/lib_NDEF_Vcard.o \
./Middlewares/lib_NDEF/lib_STProprietary_feature.o \
./Middlewares/lib_NDEF/lib_TagType4.o 

C_DEPS += \
./Middlewares/lib_NDEF/lib_ISO7816_Password.d \
./Middlewares/lib_NDEF/lib_NDEF.d \
./Middlewares/lib_NDEF/lib_NDEF_AAR.d \
./Middlewares/lib_NDEF/lib_NDEF_Email.d \
./Middlewares/lib_NDEF/lib_NDEF_Geo.d \
./Middlewares/lib_NDEF/lib_NDEF_MyApp.d \
./Middlewares/lib_NDEF/lib_NDEF_SMS.d \
./Middlewares/lib_NDEF/lib_NDEF_Text.d \
./Middlewares/lib_NDEF/lib_NDEF_URI.d \
./Middlewares/lib_NDEF/lib_NDEF_Vcard.d \
./Middlewares/lib_NDEF/lib_STProprietary_feature.d \
./Middlewares/lib_NDEF/lib_TagType4.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/lib_NDEF/lib_ISO7816_Password.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_ISO7816_Password.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_AAR.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_AAR.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_Email.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Email.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_Geo.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Geo.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_MyApp.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_MyApp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_SMS.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_SMS.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_Text.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Text.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_URI.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_URI.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_NDEF_Vcard.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_NDEF_Vcard.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_STProprietary_feature.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_STProprietary_feature.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Middlewares/lib_NDEF/lib_TagType4.o: C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/src/lib_TagType4.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/M24SR" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X-NUCLEO-NFC01A1" -I"C:/Users/adibacco/Documents/shared/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/ST/lib_NDEF/inc"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


